### ISSUE TITLE
Write Enum code

### ISSUE THREAD

**Issue by Burtorustum** [Dwight-Englewood-Robotics/0207-Relic-Recovery#1]
Create an enum for opmode selection in the init function / possibly for movement / other things?

**Comment by Weznon** [comment]
Added basic functionality https://github.com/0207-Critical-Mass/0207-Relic-Recovery/commit/e77f0d989940258771350459d0c7765645f4aea9

Should be a decent starting point for us to figure out how we're going to use while bot is being built

**Comment by Weznon** [comment]
94f2f8bd9311b7c2d9f1c666d4e0e900e0e59bf6

Started work on making a seperate package to redue clutter. Better name might be needed.

This should eventually be absorbed into

**Comment by Weznon** [comment]
Scratch above statement, since auto-gen has been moved to another repo. 

Once we know exactly the bot layout we can finalize enums.

**Comment by Weznon** [comment]
Worked a bit on the Movement enum in 7f167767552fb84c1657332bb48846a2ef75193c

This will likely need some documentation, but in brief it is an implementation of an ADT in java. This allows us to write a function which takes one object type and can have two functions. 

in haskell, it would be like

`data Movement = Forward | Backward | ... ...| Angle Int`

`driveFunction :: Movement -> Void`

and in driveFunction it can use Angle or a predetermined direction.

**Comment by Weznon** [comment]
We have most enums we need for now, we can add more as needed. Nothing interesting gained from keeping this issue open
